/**
* DRP
* This is the main server of QLM's DRP system
*
* OpenAPI spec version: 1.0.0
* Contact: akos.hollo-szabo@qlndc.hu
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package web

import io.ktor.application.ApplicationCall
import io.ktor.http.HttpMethod
import io.ktor.locations.*
import io.ktor.pipeline.PipelineContext
import io.ktor.routing.Route
import io.ktor.routing.method


// NOTE: ktor-location@0.9.0 is missing extension for Route.delete. This includes it.
inline fun <reified T : Any> Route.delete(noinline body: suspend PipelineContext<Unit, ApplicationCall>.(T) -> Unit): Route {
    return location(T::class) {
        method(HttpMethod.Delete) {
            handle(body)
        }
    }
}

object Paths {
    /**
     * get state
     * Give salesman of volume, weight, time with position for next optimisation runs
     */
    @Location("/setup/state") class getState()

    /**
     * Define setup
     * Defune setup parameters for next optimisation run
     * @param body Setup parameters 
     */
    @Location("/setup/setup") class loadSetup(val body: kotlin.String)

    /**
     * get state
     * Give salesman of volume, weight, time with position for next optimisation runs
     * @param name Name 
     */
    @Location("/state/{name}") class loadState(val name: kotlin.String)

    /**
     * Delete objective
     * delete objective specified by name
     * @param body identifier 
     */
    @Location("/setup/objective") class removeObjective(val body: kotlin.String)

    /**
     * Delete salesman
     * delete salesman specified by name
     * @param body identifier 
     */
    @Location("/setup/salesman") class removeSalesman(val body: kotlin.String)

    /**
     * get time of best result
     * get time of best plan for actual transport
     */
    @Location("/optimisation/bestCost") class getBestCost()

    /**
     * get best result
     * get best plan for actual transport
     */
    @Location("/optimisation/best") class getBestResult()

    /**
     * get root between locations
     * get best plan for actual transport
     * @param fromLat lattitude of GPS coords of source location 
     * @param fromLong longitude of GPS coords of source location 
     * @param toLat lattitude of GPS coords of target location 
     * @param toLong longitude of GPS coords of target location 
     */
    @Location("/optimisation/root/{fromLat}/{fromLong}/{toLat}/{toLong}") class getRootBetween(val fromLat: java.math.BigDecimal, val fromLong: java.math.BigDecimal, val toLat: java.math.BigDecimal, val toLong: java.math.BigDecimal)

}
