/**
* DRP
* This is the main server of QLM's DRP system
*
* OpenAPI spec version: 1.0.0
* Contact: akos.hollo-szabo@qlndc.hu
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package data.web

import data.web.GPS

/**
 * 
 * @param id 
 * @param name 
 * @param length_Meter 
 * @param root 
 */
data class Edge (
    val id: kotlin.String,
    val name: kotlin.String,
    val length_Meter: java.math.BigDecimal,
    val root: kotlin.Array<GPS>
) {

}

