/**
* DRP
* This is the main server of QLM's DRP system
*
* OpenAPI spec version: 1.0.0
* Contact: akos.hollo-szabo@qlndc.hu
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package data.web


/**
 *
 * @param id
 * @param name
 * @param center
 * @param objectives
 * @param edgesBetween
 * @param edgesFromCenter
 * @param edgesToCenter
 */
data class Graph (
    val id: String,
    val name: String,
    val center: GPS,
    val objectives: Array<Objective>,
    val edgesBetween: Array<Array<Edge>>,
    val edgesFromCenter: Array<Edge>,
    val edgesToCenter: Array<Edge>
) {

}


