/**
* DRP
* This is the main server of QLM's DRP system
*
* OpenAPI spec version: 1.0.0
* Contact: akos.hollo-szabo@qlndc.hu
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package data.web

import data.web.GPS

/**
 * 
 * @param id 
 * @param name 
 * @param location 
 * @param time_Second 
 * @param volume_Stere 
 * @param weight_Gramm 
 */
data class Objective (
    val id: kotlin.String,
    val name: kotlin.String,
    val location: GPS,
    val time_Second: java.math.BigDecimal,
    val volume_Stere: java.math.BigDecimal,
    val weight_Gramm: java.math.BigDecimal
) {

}

