/**
* DRP
* This is the main server of QLM's DRP system
*
* OpenAPI spec version: 1.0.0
* Contact: akos.hollo-szabo@qlndc.hu
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package data.web

/**
 * 
 * @param id 
 * @param name 
 * @param bestRout 
 * @param maxCost_Euro 
 * @param minCost_Euro 
 * @param bestCost_Euro 
 */
data class Progress (
    val id: kotlin.String,
    val name: kotlin.String,
    val bestRout: kotlin.Array<GPS>,
    val maxCost_Euro: java.math.BigDecimal,
    val minCost_Euro: java.math.BigDecimal,
    val bestCost_Euro: java.math.BigDecimal
) {

}

