/**
* DRP
* This is the main server of QLM's DRP system
*
* OpenAPI spec version: 1.0.0
* Contact: akos.hollo-szabo@qlndc.hu
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package data.web


/**
 * 
 * @param id 
 * @param name 
 * @param workTime_SecondPerDay 
 * @param volumeCapacity_Stere 
 * @param weightCapacity_Gramm 
 * @param vechicleSpeed_MeterPerSecond 
 * @param payment_EuroPerSecond 
 * @param fuelConsuption_LiterPerMeter 
 * @param fuelPrice_EuroPerLiter 
 * @param basePrice_Euro 
 */
data class Salesman (
    val id: kotlin.String,
    val name: kotlin.String,
    val workTime_SecondPerDay: java.math.BigDecimal,
    val volumeCapacity_Stere: java.math.BigDecimal,
    val weightCapacity_Gramm: java.math.BigDecimal,
    val vechicleSpeed_MeterPerSecond: java.math.BigDecimal,
    val payment_EuroPerSecond: java.math.BigDecimal,
    val fuelConsuption_LiterPerMeter: java.math.BigDecimal,
    val fuelPrice_EuroPerLiter: java.math.BigDecimal,
    val basePrice_Euro: java.math.BigDecimal
) {

}

