/**
* DRP
* This is the main server of QLM's DRP system
*
* OpenAPI spec version: 1.0.0
* Contact: akos.hollo-szabo@qlndc.hu
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package data.web

/**
 * 
 * @param id 
 * @param name 
 * @param iterLimit 
 * @param timeLimit_Second 
 * @param center 
 * @param objectives 
 * @param salesmen 
 */
data class Setup (
    val id: kotlin.String,
    val name: kotlin.String,
    val iterLimit: java.math.BigDecimal,
    val timeLimit_Second: java.math.BigDecimal,
    val center: GPS,
    val objectives: kotlin.Array<Objective>,
    val salesmen: kotlin.Array<Salesman>
) {

}

