/**
* DRP
* This is the main server of QLM's DRP system
*
* OpenAPI spec version: 1.0.0
* Contact: akos.hollo-szabo@qlndc.hu
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package data.web

/**
 * 
 * @param id 
 * @param name 
 * @param maxCost_Euro 
 * @param minCost_Euro 
 * @param iteration 
 * @param runtime_Second 
 * @param setup 
 * @param bestRout 
 */
data class State (
    val id: kotlin.String,
    val name: kotlin.String,
    val maxCost_Euro: java.math.BigDecimal,
    val minCost_Euro: java.math.BigDecimal,
    val iteration: java.math.BigDecimal,
    val runtime_Second: java.math.BigDecimal,
    val setup: Setup,
    val bestRout: kotlin.Array<GPS>
) {

}

