/**
* DRP
* This is the thesis.main server of QLM's DRP system
*
* OpenAPI spec version: 1.0.0
* Contact: akos.hollo-szabo@qlndc.hu
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package thesis.data.web

import java.math.BigDecimal
import java.util.*
import javax.persistence.*


/**
 * 
 * @param id 
 * @param name 
 * @param iteration 
 * @param runtime_Second 
 */
@Entity
@Table(name = "progress")
@NamedQueries(
    NamedQuery(
        name = "listProgress",
        query = "FROM Progress"
    ),
    NamedQuery(
        name = "findByNameProgress",
        query = "FROM Progress where name = :name"
    )
)
data class Progress (
    @Id
    @Column(name = "id", length = 255)
    var id: String = UUID.randomUUID().toString(),
    val name: String = "",
    val iteration: BigDecimal = BigDecimal(0),
    val runtime_Second: BigDecimal = BigDecimal(0)
) {

}

