/**
 * DRP
 * This is the thesis.main server of QLM's DRP system
 *
 * OpenAPI spec version: 1.0.0
 * Contact: akos.hollo-szabo@qlndc.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package thesis.network.apis

import io.ktor.application.call
import io.ktor.http.HttpStatusCode
import io.ktor.response.respond
import io.ktor.routing.*
import thesis.logic.OAlgorithmManager

// ktor 0.9.x is missing io.ktor.locations.DELETE, this adds it.
// see https://github.com/ktorio/ktor/issues/288

fun Route.LifecicleApi() {
    route("/lifecycle/clean") {
        post {
            OAlgorithmManager.clean()
            call.respond(HttpStatusCode.OK)
        }
    }


    route("/lifecycle/pause") {
        post {
            OAlgorithmManager.pause()
            call.respond(HttpStatusCode.OK)
        }
    }


    route("/lifecycle/prepare") {
        post {
            if(OAlgorithmManager.prepare()){
                call.respond(HttpStatusCode.OK)
            } else {
                call.respond(HttpStatusCode.MethodNotAllowed)
            }
        }
    }


    route("/lifecycle/resume") {
        post {
            OAlgorithmManager.resume()
            call.respond(HttpStatusCode.OK)
        }
    }


    route("/lifecycle/start") {
        post {
            OAlgorithmManager.start()
            call.respond(HttpStatusCode.OK)
        }
    }


    route("/lifecycle/stop") {
        post {
            OAlgorithmManager.stop()
            call.respond(HttpStatusCode.OK)
        }
    }


    route("/lifecycle/step") {
        post {
            call.respond(
                HttpStatusCode.OK,
                OAlgorithmManager.step()
            )
        }
    }


    route("/lifecycle/cycle") {
        post {
            call.respond(
                HttpStatusCode.OK,
                OAlgorithmManager.cycle()
            )
        }
    }

}
